[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/spotify-ia"
  to = "/.netlify/functions/spotifyIaProxy"
  status = 200
